site_name: Philippine Open Disaster Specification

plugins:
  - search
  - macros
  - literate-nav:
      nav_file: nav.md
      implicit_index: false
  - git-revision-date-localized:
        enable_creation_date: true
  - git-authors

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pagasa-parser/pods
  # For macros
  repo:
    url: https://github.com/pagasa-parser/pods
  typedefs: https://github.com/pagasa-parser/pods/blob/master/typedefs

repo_name: pods
repo_url: https://github.com/pagasa-parser/pods
copyright: |
  Copyright &copy; 2023&ndash;2024 Philippine Open Disaster Specification contributors. Published under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a> license.<br/>Diagram icons from FontAwesome. Copyright &copy; 2023 <a href="https://fontawesome.com">Fonticons, Inc.</a> <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. 

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - content.action.edit
